apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: working-repo
  annotations:
    github.com/project-slug: syoungs67/working-repo
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: unknown
  owner: team-a
